  #password store

apiVersion: v1 #kubernetes api version
kind: Secret # it is a secret object
metadata:
  name: cloudsql-db-credentials #name of the secret
  namespace: default 
type: Opaque
stringData: #data in plaintext 
  username: root  #db username
  password: "9bpXi&Us&:@E%}s^" #db password
